Repository iju42829/ureca-miniproject-2, pull requests merged in 2025-05, with the labels that each got.

#1 프로젝트 초기 설정
  build.gradle
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: config

#2 fit : settings.gradle
  settings.gradle
Labels: config

#4 Auditing 기반 생성 및 수정 시간 등록 기능 구현
  src/main/java/com/ureca/miniproject/common/BaseTimeEntity.java
  src/main/java/com/ureca/miniproject/common/JpaAuditingConfig.java
Labels: enhancement

#7 feature/chat
  src/main/java/com/ureca/miniproject/chat/config/WebSocketConfig.java
  src/main/java/com/ureca/miniproject/chat/controller/ChatController.java
  src/main/java/com/ureca/miniproject/chat/dto/ChatMessage.java
  src/main/resources/static/chat/chat.html
  src/main/resources/static/chat/style.css
Labels: enhancement

#9 게임방 생성 기능 구현
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/game/advice/GameRoomControllerAdvice.java
  src/main/java/com/ureca/miniproject/game/controller/GameRoomController.java
  src/main/java/com/ureca/miniproject/game/controller/request/CreateRoomRequest.java
  src/main/java/com/ureca/miniproject/game/entity/GameParticipant.java
  src/main/java/com/ureca/miniproject/game/entity/GameRoom.java
  src/main/java/com/ureca/miniproject/game/entity/ParticipantRole.java
  src/main/java/com/ureca/miniproject/game/entity/ParticipantStatus.java
  src/main/java/com/ureca/miniproject/game/entity/RoomStatus.java
  src/main/java/com/ureca/miniproject/game/repository/GameRoomRepository.java
  src/main/java/com/ureca/miniproject/game/service/GameRoomService.java
  src/main/java/com/ureca/miniproject/game/service/GameRoomServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/response/CreateGameRoomResponse.java
  src/main/java/com/ureca/miniproject/user/entity/User.java
  src/main/java/com/ureca/miniproject/user/exception/UserNotFoundException.java
  src/main/java/com/ureca/miniproject/user/repository/UserRepository.java
Labels: enhancement

#10 feat/auth
  build.gradle
  src/main/java/com/ureca/miniproject/MiniprojectApplication.java
  src/main/java/com/ureca/miniproject/config/MyAuthenticationFailureHandler.java
  src/main/java/com/ureca/miniproject/config/MyAuthenticationSuccessHandler.java
  src/main/java/com/ureca/miniproject/config/MyUserDetails.java
  src/main/java/com/ureca/miniproject/config/MyUserDetailsService.java
  src/main/java/com/ureca/miniproject/config/SecurityConfig.java
  src/main/java/com/ureca/miniproject/user/controller/CsrfController.java
  src/main/java/com/ureca/miniproject/user/controller/UserController.java
  src/main/java/com/ureca/miniproject/user/repository/UserRepository.java
  src/main/java/com/ureca/miniproject/user/service/UserServiceImpl.java
  src/main/resources/static/login.html
Labels: enhancement

#11 optional 해결
  src/main/java/com/ureca/miniproject/user/controller/UserController.java
  src/main/java/com/ureca/miniproject/user/controller/request/UserRequest.java
  src/main/java/com/ureca/miniproject/user/dto/UserResponse.java
  src/main/java/com/ureca/miniproject/user/repository/UserRepository.java
  src/main/java/com/ureca/miniproject/user/service/UserService.java
  src/main/java/com/ureca/miniproject/user/service/UserServiceImpl.java
Labels: enhancement

#12 로그인된 사용자 게임방 생성 기능 구현
  src/main/java/com/ureca/miniproject/game/controller/GameRoomController.java
  src/main/java/com/ureca/miniproject/game/service/GameRoomService.java
  src/main/java/com/ureca/miniproject/game/service/GameRoomServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/game/createGameRoom.html
Labels: enhancement

#14 게임방 목록 조회, 참여 기능 구현
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/game/advice/GameRoomControllerAdvice.java
  src/main/java/com/ureca/miniproject/game/controller/GameRoomController.java
  src/main/java/com/ureca/miniproject/game/entity/GameRoom.java
  src/main/java/com/ureca/miniproject/game/exception/AlreadyJoinedException.java
  src/main/java/com/ureca/miniproject/game/exception/GameRoomNotFoundException.java
  src/main/java/com/ureca/miniproject/game/mapper/GameRoomMapper.java
  src/main/java/com/ureca/miniproject/game/mapper/GameRoomMapperImpl.java
  src/main/java/com/ureca/miniproject/game/repository/GameParticipantRepository.java
  src/main/java/com/ureca/miniproject/game/service/GameParticipantService.java
  src/main/java/com/ureca/miniproject/game/service/GameParticipantServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/GameRoomService.java
  src/main/java/com/ureca/miniproject/game/service/GameRoomServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/response/GameRoomResponse.java
  src/main/java/com/ureca/miniproject/game/service/response/ListGameRoomResponse.java
  src/main/resources/static/game/gameRoomList.html
Labels: enhancement

#16 feat:타이머 sync 맞추고 조기종료 버튼 fix
  src/main/java/com/ureca/miniproject/chat/controller/ChatController.java
  src/main/java/com/ureca/miniproject/chat/dto/ChatMessage.java
  src/main/java/com/ureca/miniproject/config/SecurityConfig.java
  src/main/resources/static/chat/chat.html
Labels: bug, enhancement

#15 feat/auth
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/common/UnexpectedException.java
  src/main/java/com/ureca/miniproject/config/MyUserDetailsService.java
  src/main/java/com/ureca/miniproject/user/advice/UserControllerAdvice.java
  src/main/java/com/ureca/miniproject/user/controller/UserController.java
  src/main/java/com/ureca/miniproject/user/controller/request/SignUpRequest.java
  src/main/java/com/ureca/miniproject/user/controller/request/UserRequest.java
  src/main/java/com/ureca/miniproject/user/dto/Role.java
  src/main/java/com/ureca/miniproject/user/dto/UserResponse.java
  src/main/java/com/ureca/miniproject/user/dto/UserResultDto.java
  src/main/java/com/ureca/miniproject/user/entity/Role.java
  src/main/java/com/ureca/miniproject/user/entity/User.java
  src/main/java/com/ureca/miniproject/user/exception/UserAlreadyExistException.java
  src/main/java/com/ureca/miniproject/user/repository/UserRepository.java
  src/main/java/com/ureca/miniproject/user/service/UserService.java
  src/main/java/com/ureca/miniproject/user/service/UserServiceImpl.java
  src/main/java/com/ureca/miniproject/user/service/response/SignUpResponse.java
  src/main/resources/static/login.html
  src/main/resources/static/register.html
Labels: enhancement

#17 게임 상세 페이지 구현
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/common/PageController.java
  src/main/java/com/ureca/miniproject/game/controller/GameRoomController.java
  src/main/java/com/ureca/miniproject/game/mapper/GameParticipantMapper.java
  src/main/java/com/ureca/miniproject/game/mapper/GameParticipantMapperImpl.java
  src/main/java/com/ureca/miniproject/game/repository/GameParticipantRepository.java
  src/main/java/com/ureca/miniproject/game/service/GameParticipantService.java
  src/main/java/com/ureca/miniproject/game/service/GameParticipantServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/response/GameParticipantResponse.java
  src/main/java/com/ureca/miniproject/game/service/response/ListGameParticipantResponse.java
  src/main/resources/static/game/gameDetail.html
  src/main/resources/static/game/gameRoomList.html
Labels: enhancement

#18 게임에 참여 중인 경우 게임 상세페이지로 이동
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/game/controller/GameRoomController.java
  src/main/java/com/ureca/miniproject/game/repository/GameParticipantRepository.java
  src/main/java/com/ureca/miniproject/game/service/GameParticipantService.java
  src/main/java/com/ureca/miniproject/game/service/GameParticipantServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/response/ParticipantCheckResponse.java
  src/main/resources/static/game/gameRoomList.html
Labels: bug, enhancement

#19 게임방 나가기,삭제 및 방장 판별 기능 구현
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/game/controller/GameParticipantController.java
  src/main/java/com/ureca/miniproject/game/controller/GameRoomController.java
  src/main/java/com/ureca/miniproject/game/entity/GameRoom.java
  src/main/java/com/ureca/miniproject/game/exception/GameRoomDeleteForbiddenException.java
  src/main/java/com/ureca/miniproject/game/exception/GameRoomNotWaitingException.java
  src/main/java/com/ureca/miniproject/game/repository/GameParticipantRepository.java
  src/main/java/com/ureca/miniproject/game/service/GameParticipantService.java
  src/main/java/com/ureca/miniproject/game/service/GameParticipantServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/GameRoomService.java
  src/main/java/com/ureca/miniproject/game/service/GameRoomServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/response/GameRoomDetailResponse.java
  src/main/resources/static/game/gameDetail.html
Labels: enhancement

#21 fix : principal에서 username 읽어오는 부분
  src/main/java/com/ureca/miniproject/chat/controller/ChatController.java
Labels: bug

#22 게임방 최대 참여 인원 제한 및 게임 시작 기능 추가
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/game/controller/GameController.java
  src/main/java/com/ureca/miniproject/game/controller/GameParticipantController.java
  src/main/java/com/ureca/miniproject/game/entity/GameRoom.java
  src/main/java/com/ureca/miniproject/game/exception/GameRoomCapacityExceededException.java
  src/main/java/com/ureca/miniproject/game/repository/GameRoomRepository.java
  src/main/java/com/ureca/miniproject/game/service/GameRoomServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/GameService.java
  src/main/java/com/ureca/miniproject/game/service/GameServiceImpl.java
  src/main/resources/static/game/gameDetail.html
  src/main/resources/static/game/gameRoomList.html
Labels: enhancement

#23 게임 시작 시 채팅 화면 이동 구현
  src/main/java/com/ureca/miniproject/game/service/GameRoomServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/response/GameRoomDetailResponse.java
  src/main/resources/static/game/gameDetail.html
Labels: enhancement

#24 fix : roomid 받아오기
  src/main/java/com/ureca/miniproject/game/controller/GameController.java
  src/main/java/com/ureca/miniproject/game/controller/GameParticipantController.java
  src/main/java/com/ureca/miniproject/game/controller/GameRoomController.java
  src/main/resources/application.yml
  src/main/resources/static/chat/chat.html
  src/main/resources/static/game/gameDetail.html
  src/main/resources/static/login.html
Labels: bug

#25 게임 참가자 죽음 처리
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/game/controller/GameController.java
  src/main/java/com/ureca/miniproject/game/exception/GameParticipantNotFoundException.java
  src/main/java/com/ureca/miniproject/game/repository/GameParticipantRepository.java
  src/main/java/com/ureca/miniproject/game/service/GameService.java
  src/main/java/com/ureca/miniproject/game/service/GameServiceImpl.java
  src/main/java/com/ureca/miniproject/user/repository/UserRepository.java
Labels: enhancement

#28 게임 전적 저장 및 조회 기능 구현
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/game/controller/GameController.java
  src/main/java/com/ureca/miniproject/game/controller/request/EndGameRequest.java
  src/main/java/com/ureca/miniproject/game/entity/GameResult.java
  src/main/java/com/ureca/miniproject/game/entity/GameResultStatus.java
  src/main/java/com/ureca/miniproject/game/repository/GameResultRepository.java
  src/main/java/com/ureca/miniproject/game/service/GameService.java
  src/main/java/com/ureca/miniproject/game/service/GameServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/response/GameResultResponse.java
  src/main/java/com/ureca/miniproject/game/service/response/ListGameResultResponse.java
Labels: enhancement

#29 게임 도메인 예외 처리 핸들러 추가
  src/main/java/com/ureca/miniproject/game/advice/GameControllerAdvice.java
  src/main/java/com/ureca/miniproject/game/advice/GameRoomControllerAdvice.java
Labels: enhancement

#30 feat:vote
  src/main/java/com/ureca/miniproject/chat/controller/ChatController.java
  src/main/java/com/ureca/miniproject/chat/controller/VoteController.java
  src/main/java/com/ureca/miniproject/chat/dto/GameState.java
  src/main/java/com/ureca/miniproject/chat/dto/VoteResultDto.java
  src/main/java/com/ureca/miniproject/chat/service/VoteService.java
  src/main/resources/static/chat/chat.html
Labels: enhancement

#31 feat : 받은 친구 신청 list up
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/friend/controller/FriendController.java
  src/main/java/com/ureca/miniproject/friend/controller/request/ListFriendRequest.java
  src/main/java/com/ureca/miniproject/friend/controller/request/UpdateFriendRequest.java
  src/main/java/com/ureca/miniproject/friend/repository/FriendRepository.java
  src/main/java/com/ureca/miniproject/friend/service/FriendService.java
  src/main/java/com/ureca/miniproject/friend/service/FriendServiceImpl.java
  src/main/java/com/ureca/miniproject/friend/service/response/ListFriendResponse.java
  src/main/java/com/ureca/miniproject/friend/service/response/updateFriendResponse.java
  src/main/resources/static/friend/inviteFriend.html
Labels: enhancement

#32 fix : Rename updateFriendResponse.java to UpdateFriendResponse.java
  src/main/java/com/ureca/miniproject/friend/service/response/UpdateFriendResponse.java
Labels: bug

#33 게임 리포지토리 테스트 추가
  .gitignore
  build.gradle
  src/test/java/com/ureca/miniproject/game/repository/GameParticipantRepositoryTest.java
  src/test/java/com/ureca/miniproject/game/repository/GameResultRepositoryTest.java
  src/test/java/com/ureca/miniproject/game/repository/GameRoomRepositoryTest.java
Labels: test

#34 feat:game manager/timer
  src/main/java/com/ureca/miniproject/chat/controller/ChatController.java
  src/main/java/com/ureca/miniproject/chat/controller/GameStateController.java
  src/main/java/com/ureca/miniproject/chat/service/StateManager.java
  src/main/resources/static/chat/chat.html
Labels: enhancement

#35 Feat : state machine/chat
  src/main/java/com/ureca/miniproject/chat/controller/ChatController.java
  src/main/java/com/ureca/miniproject/chat/controller/GameStateController.java
  src/main/java/com/ureca/miniproject/chat/service/StateManager.java
  src/main/resources/static/chat/chat.html
Labels: enhancement

#42 게임방 및 참가 서비스 레이어 테스트 추가
  src/main/java/com/ureca/miniproject/game/exception/AlreadyJoinedException.java
  src/main/java/com/ureca/miniproject/game/exception/GameRoomNotFoundException.java
  src/main/java/com/ureca/miniproject/user/exception/UserNotFoundException.java
  src/test/java/com/ureca/miniproject/game/service/GameParticipantServiceTest.java
  src/test/java/com/ureca/miniproject/game/service/GameRoomServiceTest.java
Labels: enhancement

#43 게임방 참가자 정보 조회 api 구현
  src/main/java/com/ureca/miniproject/game/controller/GameParticipantController.java
  src/main/java/com/ureca/miniproject/game/mapper/GameParticipantMapper.java
  src/main/java/com/ureca/miniproject/game/mapper/GameParticipantMapperImpl.java
  src/main/java/com/ureca/miniproject/game/service/GameParticipantService.java
  src/main/java/com/ureca/miniproject/game/service/GameParticipantServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/response/DetailGameParticipantResponse.java
Labels: enhancement

#44 비관적 락을 이용해 게임방 인원 동시성 문제 해결
  src/main/java/com/ureca/miniproject/game/repository/GameRoomRepository.java
  src/main/java/com/ureca/miniproject/game/service/GameRoomServiceImpl.java
  src/main/resources/static/game/gameDetail.html
Labels: bug

#45 feat : logout 기능, 친구 관리 기능을 게임방 리스트 페이지에 모달로 추가
  src/main/java/com/ureca/miniproject/config/SecurityConfig.java
  src/main/java/com/ureca/miniproject/friend/controller/FriendController.java
  src/main/java/com/ureca/miniproject/friend/repository/FriendRepository.java
  src/main/java/com/ureca/miniproject/friend/service/FriendServiceImpl.java
  src/main/java/com/ureca/miniproject/friend/service/response/UpdateFriendResponse.java
  src/main/resources/static/friend/inviteFriend.html
  src/main/resources/static/game/gameRoomList.html
  src/main/resources/static/index.html
Labels: enhancement

#47 게임방 레이아웃 개선
  src/main/resources/static/game/createGameRoom.html
  src/main/resources/static/game/gameDetail.html
  src/main/resources/static/game/gameRoomList.html
Labels: bug, refactor

#48 test : friend/repository 의 test code 생성
  src/main/java/com/ureca/miniproject/friend/repository/FriendRepository.java
  src/main/java/com/ureca/miniproject/friend/service/FriendServiceImpl.java
  src/main/resources/static/game/gameRoomList.html
  src/main/resources/static/login.html
  src/test/java/com/ureca/miniproject/friend/repository/FriendRepositoryTest.java
Labels: test

#49 게임 서비스 레이어 테스트 추가
  src/main/java/com/ureca/miniproject/game/controller/request/EndGameRequest.java
  src/main/java/com/ureca/miniproject/game/entity/GameParticipant.java
  src/test/java/com/ureca/miniproject/game/service/GameServiceTest.java
Labels: bug, test

#51 Dockerfile 및 docker-compose 설정 추가
  .gitignore
  Dockerfile
  docker-compose.yml
Labels: config

#53 게임 종료 여부 확인 API 구현
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/game/controller/GameController.java
  src/main/java/com/ureca/miniproject/game/service/GameService.java
  src/main/java/com/ureca/miniproject/game/service/GameServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/response/EndStatusResponse.java
Labels: enhancement

#54 게임 종료 상태 구조 변경
  src/main/java/com/ureca/miniproject/game/service/GameServiceImpl.java
  src/main/java/com/ureca/miniproject/game/service/response/EndStatus.java
  src/main/java/com/ureca/miniproject/game/service/response/EndStatusResponse.java
Labels: bug

#57 게임 참가자에 경찰 역할 추가
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/game/advice/GameControllerAdvice.java
  src/main/java/com/ureca/miniproject/game/entity/ParticipantRole.java
  src/main/java/com/ureca/miniproject/game/exception/NotEnoughParticipantsException.java
  src/main/java/com/ureca/miniproject/game/service/GameServiceImpl.java
Labels: enhancement

#58 README.md 추가
  README.md
Labels: documentation

#60 회원가입, 로그인, 메인페이지 ui 구조 개선
  src/main/resources/static/index.html
  src/main/resources/static/login.html
  src/main/resources/static/register.html
Labels: refactor

#62 로그인 상태에 따라 버튼 표시 제어
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/common/StatusController.java
  src/main/java/com/ureca/miniproject/config/SecurityConfig.java
  src/main/resources/static/index.html
Labels: enhancement

#61 프로젝트 ERD 추가
  README.md
Labels: documentation

#67 fix:final..?
  src/main/java/com/ureca/miniproject/chat/controller/NightController.java
  src/main/java/com/ureca/miniproject/chat/controller/VoteController.java
  src/main/java/com/ureca/miniproject/chat/service/VoteService.java
  src/main/resources/static/chat/chat.html
Labels: bug

#68 Feat : invite game room
  src/main/java/com/ureca/miniproject/common/BaseCode.java
  src/main/java/com/ureca/miniproject/common/PageController.java
  src/main/java/com/ureca/miniproject/friend/controller/FriendController.java
  src/main/java/com/ureca/miniproject/friend/service/FriendServiceImpl.java
  src/main/java/com/ureca/miniproject/game/repository/GameParticipantRepository.java
  src/main/java/com/ureca/miniproject/user/controller/UserController.java
  src/main/java/com/ureca/miniproject/user/controller/request/InviteUserRequest.java
  src/main/java/com/ureca/miniproject/user/service/UserService.java
  src/main/java/com/ureca/miniproject/user/service/UserServiceImpl.java
  src/main/java/com/ureca/miniproject/user/service/response/InvitesUserResponse.java
  src/main/java/com/ureca/miniproject/user/service/response/ProposeUserResponse.java
  src/main/resources/application.yml
  src/main/resources/static/game/gameDetail.html
  src/main/resources/static/index.html
  src/main/resources/static/user/inviteGameRoom.html
Labels: enhancement
